import styles from "./index.module.css"
import { type NextPage } from "next"
import Head from "next/head"
// import Link from "next/link"
import { signIn, signOut, useSession } from "next-auth/react"
import { Button, Space } from 'antd'


const LandingPage: NextPage = () => {
  const { data: sessionData } = useSession()
  return (
    <>
      <Head>
        <title>StablePrompts</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <h1 className={styles.title}>StablePrompts</h1>
          <Space wrap>
            <Button
              type={sessionData ? "link" : "primary"}
              onClick={sessionData ? () => void signOut() : () => void signIn()}
            >
              {sessionData ? "Sign out" : "Sign in"}
            </Button>
          </Space>
        </div>
      </main>
    </>
  )
}

export default LandingPage
