import styles from "~/styles/index.module.css"

import { type NextPage } from "next"
import Head from "next/head"
import { signIn, signOut, useSession } from "next-auth/react"
import Button from 'react-bootstrap/Button'

import Footer from '../components/Footer'


const LandingPage: NextPage = () => {
  const { data: sessionData } = useSession()

  return (
    <>
      <Head>
        <title>StablePrompts</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <h1 className={styles.title}>StablePrompts</h1>
          {
            sessionData &&
              <Button variant="primary" href="/dashboard">
                Dashboard
              </Button>
          }
          <Button
            variant={sessionData ? "link" : "primary"}
            onClick={sessionData ? () => void signOut() : () => void signIn()}
          >
            {sessionData ? "Sign out" : "Sign in"}
          </Button>
        </div>
        <Footer />
      </main>
    </>
  )
}

export default LandingPage
