// import styles from "./app.module.css"
import { type NextPage } from "next"
import Head from "next/head"
import Link from "next/link"
import { signIn, signOut, useSession } from "next-auth/react"
import { Table } from "antd"
import { api } from "~/utils/api"


const Prompts: NextPage = () => {

const dataSource = [
  {
    key: '1',
    prompt: 'Mike',
    created: 32,
    updated: '10 Downing Street',
  },
  {
    key: '2',
    prompt: 'John',
    created: 42,
    updated: '10 Downing Street',
  },
];

const columns = [
  {
    title: 'ID',
    dataIndex: 'key',
    key: 'id',
  },
  {
    title: 'Prompt',
    dataIndex: 'prompt',
    key: 'prompt',
  },
  {
    title: 'Created',
    dataIndex: 'created',
    key: 'created',
  },
];

  return (
    <>
      <Head>
        <title>Prompts</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          <h1>
            Prompts
          </h1>
          <Table dataSource={dataSource} columns={columns} />;
        </div>
      </main>
    </>
  );
};

export default Prompts

